version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: user-prod-redis-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: postgres
    ports:
      - "5974:5432"   
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: ddoc-redis-1
    ports:
      - "6379:6379"  
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod-user-redis
    ports:
      - "9999:9999" 
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?autoreconnect=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwe
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 9999

networks:
  app-network:
    driver: bridge
