name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and package application
        run: mvn clean package

      - name: Verify JAR file exists
        run: ls -l target

      - name: Show working directory
        run: pwd

      - name: Show files in working directory
        run: ls -l

      - name: Build Docker image
        run: docker build -t nikitkamzgb/project01-prod-user-redis:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u nikitkamzgb -p vopule3737
          docker push nikitkamzgb/project01-prod-user-redis:latest

